version: '3.8'
services:
  app:
    container_name: javaBootCampAdv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8050
      - 5005:5005
    depends_on:
      - redis
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: dev
      LOGGING_LEVEL: DEBUG
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth

  redis:
    image: redis:latest
    ports:
      - 6378:6379

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10

  postgres:
    image: postgres:latest
    ports:
      - 5431:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

volumes:
  postgres-data: